# .github/workflows/deploy-pages.yml

name: Deploy Logomaker Web to GitHub Pages

on:
  push:
    branches: [ "master" ] # Or 'main'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write      # Permission to deploy to Pages
  id-token: write   # Permission for OIDC token used by deploy-pages

# Allow only one concurrent deployment to Pages, cancel older runs
concurrency:
  group: "pages" # Use the standard 'pages' concurrency group
  cancel-in-progress: true

jobs:
  # Build job for the WEB version
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # Still need LFS for font generation source

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Install Dependencies
        run: npm ci # Install devDeps needed by build scripts

      # --- Build the DEPLOY target (NOT portable) ---
      - name: Build Logomaker for GitHub Pages
        run: npm run build:deploy
        # This builds the optimized web version into ./dist/github-pages

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # --- Upload the CORRECT artifact for Pages ---
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the contents of the deploy build output
          path: './dist/github-pages'

  # Deployment job for Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Output the deployed URL
    runs-on: ubuntu-latest
    needs: build # Wait for the build job
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # This action automatically uses the artifact uploaded above