name: Release Desktop GUI

on:
  push:
    branches:
      - master

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'desktop:')
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add Go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd desktop
          mkdir -p ../build/${{ matrix.goos }}_${{ matrix.goarch }}
          wails build -platform ${{ matrix.goos }}/${{ matrix.goarch }} -o ../build/${{ matrix.goos }}_${{ matrix.goarch }}/app

      - name: Archive builds
        run: |
          cd build/${{ matrix.goos }}_${{ matrix.goarch }}
          zip -r ../../app-${{ matrix.goos }}-${{ matrix.goarch }}.zip .
          cd ../..

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release from desktop commit
          tag_name: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app-linux-amd64.zip
            app-windows-amd64.zip
            app-darwin-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
